
lescadusermatiereadd:
  path: /profile/addmatiere
  defaults:
      _controller: lescaduserBundle:Formation:addmatiere

lescaduserformationadd:
  path: /profile/addformation
  defaults:
      _controller: lescaduserBundle:Formation:addformation

lescadusercategorieadd:
  path: /profile/addcategorie
  defaults:
      _controller: lescaduserBundle:Formation:addcategorie
      
 
