<?php

namespace lescad\platformeBundle\Repository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindAllWithFormations()
    {
      $qb = $this
        ->createQueryBuilder('c')
        ->leftJoin('c.formations', 'f')
        ->addSelect('f')
        ->orderBy('c.nom', 'ASC')
      ;
    
      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
