<?php

namespace lescad\platformeBundle\Repository;

/**
 * DemandeRecrutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRecrutRepository extends \Doctrine\ORM\EntityRepository
{
}
