<?php

namespace lescad\platformeBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderedQueryBuilder()
  {
    return $this
      ->createQueryBuilder('d')
      ->orderBy('d.nom', 'ASC')
    ;
  }
}
