<?php

namespace lescad\platformeBundle\Repository;

/**
 * serviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SssRepository extends \Doctrine\ORM\EntityRepository
{
}
