<?php

namespace lescad\platformeBundle\Repository;

/**
 * DemandeCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
